
#==========================  Modules configuration ============================
metricbeat.modules:
#------------------------------- php_fpm Module ------------------------------
- module: php_fpm
  metricsets: ["pool"]
  enabled: true
  period: 10s
  status_path: "/status"
  hosts: ["localhost:8080"]
